version: '3.5'

services:
  postgres:
    container_name: postgres_leo
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-LeoDB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      PGDATA: /data/postgres_leo
    volumes:
      - postgres:/data/postgres_leo
    ports:
      - '5432:5432'
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
